// A broad bank of everyday words a fourth grader is likely to recognize. It is
// the single source of real words the game draws from; progression.js filters
// it down to whatever letters are currently unlocked, so this is intentionally
// a flat, letter-agnostic list rather than being split by keyboard row.
//
// Keep every entry lowercase and a-z only. Capitals, digits, and punctuation
// are layered on by the round generator at later stages — a raw apostrophe or
// hyphen here would just make a word ineligible until those stages unlock. The
// list is kept alphabetical so it's easy to scan for gaps or duplicates. New
// entries should be real, correctly-spelled words; the bank is validated against
// a dictionary (see scripts history) to guard against typos.
export const WORD_BANK = [
  "aardvark", "about", "absent", "absurd", "accept", "ache", "achieve", "acid", "acorn", "acre",
  "acrobat", "active", "actor", "actress", "actual", "add", "admire", "adopt", "adorable",
  "adore", "ads", "adventurous", "advise", "afraid", "after", "afternoon", "again", "agree",
  "aim", "airplane", "airport", "alas", "all", "alley", "alligator", "allow", "almanac",
  "almond", "almost", "alpaca", "alphabet", "already", "also", "although", "altogether",
  "always", "am", "amaze", "amber", "ambulance", "amuse", "an", "anchor", "ancient", "anger",
  "angry", "ankle", "announce", "annoy", "annoyed", "annoying", "anorak", "another", "answer",
  "ant", "anteater", "antelope", "antenna", "anthem", "anthill", "anxious", "any", "anybody",
  "anyhow", "anymore", "anyone", "anyplace", "anything", "anytime", "anyway", "anywhere",
  "apart", "apartment", "ape", "apologize", "appear", "appetite", "applaud", "apple", "approach",
  "approve", "apricot", "apron", "aqua", "aquarium", "arcade", "arch", "archer", "archery",
  "architect", "archway", "arctic", "arena", "argue", "argument", "arithmetic", "arm",
  "armadillo", "armpit", "aroma", "around", "arrange", "arrest", "arrive", "arrow", "artichoke",
  "artist", "as", "ash", "ashamed", "aside", "ask", "asleep", "asparagus", "assemble",
  "assignment", "assist", "astronaut", "at", "athlete", "athletic", "atlas", "atmosphere",
  "atom", "attach", "attack", "attempt", "attend", "attention", "attic", "attract", "auditorium",
  "aunt", "aurora", "author", "automobile", "autumn", "avalanche", "avenue", "average",
  "aviation", "avocado", "avoid", "awake", "awaken", "away", "awesome", "awful", "awkward",
  "awning", "ax", "axle", "baboon", "baby", "back", "backbone", "backpack", "backward", "bacon",
  "bad", "badger", "badminton", "bagel", "baggage", "bake", "baker", "bakery", "balance",
  "balcony", "ballcap", "ballet", "balloon", "ballpoint", "bamboo", "banana", "bandana",
  "bandstand", "bang", "banister", "bank", "banker", "baptize", "barbecue", "barber", "barely",
  "bargain", "barge", "bark", "barn", "barometer", "barrel", "baseball", "basement", "basil",
  "basket", "basketball", "bat", "bathe", "bathroom", "bathtub", "batter", "battery", "batting",
  "battle", "bay", "bazaar", "be", "beach", "beacon", "beagle", "beaker", "bean", "beans",
  "bear", "beard", "beautiful", "beauty", "beaver", "because", "beckon", "bed", "bedroom",
  "beef", "beehive", "been", "beetle", "before", "beforehand", "beg", "behave", "behavior",
  "behind", "being", "belief", "believe", "bell", "belly", "belong", "below", "belt", "bench",
  "bend", "bendy", "beneath", "beret", "berry", "beside", "besides", "best", "between", "beyond",
  "bib", "bicycle", "big", "bike", "binder", "binoculars", "biology", "bird", "biscuit", "bison",
  "bite", "bitter", "black", "blackbird", "blackboard", "blacksmith", "bladder", "blame",
  "blank", "blanket", "blaring", "blaze", "blazer", "blazing", "bleachers", "bleak", "blend",
  "blender", "bless", "blessing", "blimp", "blinds", "blink", "blissful", "blister", "blizzard",
  "blond", "bloodstream", "bloom", "blossom", "blouse", "blow", "blue", "blueberry", "bluebird",
  "blueprint", "blunt", "blurry", "blush", "boar", "boarding", "boardwalk", "boast", "boat",
  "bobcat", "bobsled", "bog", "boil", "boiling", "bold", "bologna", "bolt", "bone", "bonnet",
  "book", "bookcase", "bookmark", "bookshelf", "boot", "booth", "bootie", "bored", "boring",
  "borrow", "bossy", "both", "bother", "bottle", "boulder", "boulevard", "bounce", "boundary",
  "bow", "bowl", "bowling", "box", "boxcar", "boxing", "boy", "bracelet", "brag", "braid",
  "brain", "brainy", "brake", "bramble", "bran", "branch", "brand", "brass", "brave", "bravery",
  "brawny", "bread", "break", "breakfast", "breathe", "breed", "breeze", "breezy", "brew",
  "bridge", "brief", "briefly", "bright", "brighten", "brilliant", "bring", "brisk", "bristle",
  "broadcast", "broccoli", "broil", "broken", "bronze", "broom", "broth", "brother", "brown",
  "brownie", "bruise", "brunch", "brush", "bubble", "bubbly", "bucket", "buckle", "bud",
  "buffalo", "bug", "bugle", "build", "builder", "bulky", "bull", "bulldog", "bulldozer",
  "bulletin", "bullfrog", "bully", "bumblebee", "bump", "bumper", "bumpy", "bun", "bundle",
  "bunker", "bunny", "bureau", "burly", "burn", "burrow", "bury", "bus", "bush", "bustle",
  "busy", "butcher", "butter", "butterfly", "buttery", "button", "buy", "buzz", "buzzard", "by",
  "cab", "cabbage", "cabin", "cabinet", "caboose", "cactus", "cafeteria", "cage", "cake",
  "calculate", "calculator", "calendar", "calf", "call", "calm", "came", "camel", "camp",
  "campfire", "campsite", "canary", "cancel", "candle", "candy", "cannon", "canoe", "cantaloupe",
  "canyon", "cap", "cape", "capital", "captain", "capture", "car", "caramel", "caravan",
  "carbon", "cardboard", "cardigan", "cardinal", "care", "careful", "careless", "cargo",
  "caribou", "carnival", "carousel", "carp", "carpenter", "carpet", "carriage", "carrot",
  "carry", "cartwheel", "carve", "cashier", "casserole", "castle", "cat", "catch", "catcher",
  "caterpillar", "catfish", "cathedral", "cauldron", "cauliflower", "cautious", "cave", "cavern",
  "cavity", "cease", "ceiling", "celebrate", "celery", "cellar", "cement", "centipede",
  "century", "ceramic", "cereal", "ceremony", "certainly", "chair", "chalet", "chalk",
  "chalkboard", "challenge", "chamber", "chameleon", "chance", "chandelier", "change", "chant",
  "chaos", "chapel", "chapter", "charge", "chariot", "charity", "charm", "chart", "chase",
  "chatter", "chatty", "cheap", "cheat", "checkers", "cheddar", "cheek", "cheekbone", "cheer",
  "cheerful", "cheese", "cheetah", "chef", "chemical", "cherish", "cherry", "chess", "chest",
  "chestnut", "chew", "chewy", "chick", "chickadee", "chief", "child", "childhood", "childish",
  "chili", "chilly", "chime", "chimney", "chimp", "chimpanzee", "chin", "chinchilla", "chip",
  "chipmunk", "chirp", "chocolate", "choice", "choke", "choose", "chop", "chopper", "chowder",
  "chubby", "chuckle", "chunky", "church", "cider", "cinnamon", "circuit", "circular", "circus",
  "citadel", "citizen", "city", "cityscape", "claim", "clam", "clamp", "clap", "clarify",
  "clash", "clasp", "class", "classic", "classify", "classmate", "classroom", "clay", "clean",
  "cleanse", "clear", "clearly", "clench", "clerk", "clever", "cliff", "climate", "climb",
  "cling", "clinic", "clip", "clipboard", "cloak", "clock", "clog", "close", "closely", "closet",
  "cloud", "clove", "clover", "clown", "clumsy", "clutch", "coach", "coarse", "coast", "coat",
  "coax", "cobbler", "cobblestone", "cobra", "cobweb", "cockpit", "cocoa", "coconut", "cocoon",
  "cold", "coleslaw", "coliseum", "collapse", "collar", "collarbone", "collect", "college",
  "collide", "colon", "colony", "color", "colorful", "colossal", "colt", "column", "comb",
  "combine", "come", "comet", "comfort", "comforter", "comfy", "comical", "comma", "command",
  "commit", "commonly", "community", "compare", "compass", "compete", "complain", "complete",
  "completely", "complex", "compose", "composer", "composition", "conceal", "concern",
  "conclude", "condor", "conductor", "confess", "confidence", "confident", "confirm", "confuse",
  "confused", "congratulate", "connect", "consider", "constantly", "constellation", "construct",
  "consume", "contain", "content", "continue", "contribute", "control", "convertible",
  "convince", "cook", "cooked", "cookie", "cool", "cooperate", "copper", "copy", "coral",
  "corduroy", "corn", "cornbread", "correct", "correctly", "corridor", "costume", "cottage",
  "cotton", "couch", "cougar", "cough", "could", "counselor", "count", "countertop", "county",
  "courage", "courtyard", "cousin", "cove", "cow", "cowboy", "coyote", "cozy", "crab", "crack",
  "cracked", "cracker", "crackle", "crafty", "cram", "cranberry", "crane", "cranky", "crash",
  "crate", "crater", "crave", "crawl", "crayon", "crazy", "creaky", "cream", "creamy", "create",
  "creative", "creek", "creep", "creepy", "crest", "crevice", "cricket", "cringe", "crinkle",
  "crisis", "crisp", "croak", "crocodile", "crooked", "crossing", "crossroads", "crouch",
  "crouton", "crow", "crowd", "crowded", "cruise", "crumb", "crumble", "crumbly", "crumple",
  "crunch", "crunchy", "crush", "crust", "crusty", "cry", "crystal", "cub", "cuckoo", "cucumber",
  "cuddle", "cuddly", "culture", "cunning", "cup", "cupboard", "curb", "cure", "curiosity",
  "curious", "curl", "curly", "currently", "cursive", "curtain", "curve", "curved", "cushion",
  "cushy", "custard", "cut", "cute", "cycle", "cylinder", "dab", "dad", "daily", "dairy", "dam",
  "damage", "damp", "dampen", "dance", "dancer", "dandelion", "danger", "dangle", "daring",
  "dark", "darkness", "dart", "dash", "dashboard", "dawn", "day", "daydream", "daytime",
  "dazzle", "dazzling", "deadly", "deal", "decade", "decay", "deceive", "decent", "decide",
  "decision", "decorate", "decrease", "deep", "deeply", "deer", "defeat", "defend", "definitely",
  "definition", "delay", "delicate", "delicious", "delight", "delightful", "deliver", "delta",
  "demand", "denim", "dense", "dentist", "depart", "depend", "depot", "describe", "desert",
  "deserve", "design", "designer", "desire", "desk", "dessert", "destination", "destiny",
  "destroy", "detect", "detective", "detention", "determine", "develop", "devour", "dew",
  "dewdrop", "diagram", "dial", "diameter", "diamond", "diaper", "diary", "dictionary", "diesel",
  "different", "difficult", "dig", "digital", "diligent", "dim", "dimple", "dine", "dinghy",
  "dingy", "dinner", "dinosaur", "dip", "diploma", "direct", "directly", "director", "dirt",
  "dirty", "disagree", "disappear", "disappoint", "disaster", "discover", "discovery", "discuss",
  "disguise", "dish", "dishwasher", "dislike", "dismal", "dismiss", "display", "dissolve",
  "distance", "distant", "distract", "disturb", "dive", "divide", "division", "dizzy", "do",
  "dock", "doctor", "dodge", "dodgeball", "does", "dog", "dogsled", "dolphin", "donate", "done",
  "donkey", "donut", "doodle", "door", "doorbell", "doorknob", "doormat", "doorway", "dopey",
  "double", "doubt", "doubtful", "dough", "dove", "down", "downstairs", "downtown", "downward",
  "dozen", "drag", "dragonfly", "drain", "dramatic", "drapes", "draw", "drawbridge", "drawer",
  "drawing", "dread", "dreadful", "dream", "dreary", "drench", "dress", "dresser", "dressing",
  "dribble", "drift", "drill", "drink", "drip", "dripping", "drive", "driveway", "drizzle",
  "drool", "droop", "drop", "drought", "drown", "drowsy", "drum", "drummer", "dry", "dryer",
  "duck", "duckling", "dugout", "dull", "dumbbell", "dump", "dumpling", "dune", "dungarees",
  "dungeon", "during", "dusk", "dust", "dusty", "duty", "dwell", "dwelling", "each", "eager",
  "eagerness", "eagle", "ear", "eardrum", "earlobe", "early", "earmuffs", "earn", "earring",
  "earth", "earthquake", "earthworm", "earthy", "earwig", "ease", "easily", "easy", "eat",
  "echo", "eclipse", "edgy", "editor", "eel", "effort", "egg", "eggplant", "egret", "eight",
  "elastic", "elbow", "elderly", "elect", "electric", "electrician", "electricity", "elegant",
  "element", "elephant", "elk", "else", "elsewhere", "embassy", "ember", "embrace", "empty",
  "emu", "encourage", "endless", "endure", "energetic", "energy", "engine", "engineer", "enjoy",
  "enormous", "enter", "entertain", "enthusiasm", "entire", "entirely", "entrance", "envious",
  "envy", "equal", "equally", "equator", "eraser", "escalator", "escape", "especially", "essay",
  "even", "evening", "eventually", "ever", "evergreen", "every", "everybody", "everyday",
  "everyone", "everything", "everywhere", "evil", "exact", "exactly", "exam", "examine",
  "excellent", "exchange", "excite", "excited", "excitement", "excuse", "exercise", "exhale",
  "exist", "exotic", "expand", "expect", "expensive", "experiment", "explain", "explode",
  "explore", "explorer", "express", "expressway", "extend", "extra", "extremely", "eye",
  "eyebrow", "eyelash", "eyelid", "fable", "face", "factory", "fade", "fail", "faint", "fair",
  "fairground", "fairly", "faith", "faithful", "fake", "falcon", "fall", "fame", "family",
  "famous", "fancy", "fantastic", "faraway", "farm", "farmer", "fast", "fasten", "father",
  "favor", "fawn", "fear", "fearful", "fearless", "feast", "feeble", "feed", "feel", "fence",
  "fencing", "fern", "ferret", "ferry", "ferryboat", "festive", "fetch", "fever", "few",
  "fiction", "fidget", "field", "fierce", "fiery", "fig", "fight", "fill", "fillet", "film",
  "filter", "filthy", "final", "finally", "finch", "find", "fine", "finger", "fingernail",
  "fingertip", "finish", "firefighter", "firefly", "firehouse", "fireplace", "firm", "firmly",
  "first", "fish", "fisherman", "five", "fix", "fjord", "flag", "flagpole", "flaky", "flame",
  "flamingo", "flannel", "flap", "flash", "flashlight", "flashy", "flask", "flat", "flatten",
  "flavor", "flawless", "flea", "flee", "fleecy", "flexible", "flick", "flicker", "flimsy",
  "fling", "flip", "float", "flood", "floorboard", "flop", "floppy", "florist", "flounder",
  "flour", "flourish", "flow", "flower", "fluffy", "flunk", "flush", "flutter", "fly", "foal",
  "foamy", "fog", "foggy", "fold", "folder", "foliage", "follow", "fond", "foolish", "foot",
  "football", "foothill", "forbid", "force", "forecast", "forehead", "forest", "forever",
  "forget", "forgetful", "forgive", "fork", "forklift", "form", "formal", "formerly", "fort",
  "fortress", "fortunate", "fortunately", "fortune", "forward", "fossil", "found", "fountain",
  "four", "fox", "foyer", "fraction", "fragile", "fragrant", "frail", "frame", "frankly",
  "frantic", "freckle", "freckled", "freedom", "freely", "freeway", "freeze", "freezer",
  "freezing", "freighter", "frequent", "frequently", "fresh", "friction", "friend", "friendly",
  "friendship", "fries", "frighten", "frightened", "frilly", "frisbee", "frisky", "frizzy",
  "frog", "frolic", "from", "frost", "frosting", "frosty", "frown", "frozen", "frugal", "fruit",
  "fruity", "fuel", "full", "fumble", "fund", "fungus", "funhouse", "funnel", "funny", "furious",
  "furnace", "furniture", "furry", "future", "fuzzy", "gal", "galaxy", "gallery", "gallop",
  "gameboard", "garage", "garden", "gardener", "garlic", "gas", "gash", "gasoline", "gasp",
  "gate", "gateway", "gather", "gaudy", "gave", "gaze", "gazebo", "gazelle", "gear", "gearshift",
  "gecko", "gem", "generator", "generosity", "generous", "gentle", "gently", "genuine",
  "geography", "geologist", "gerbil", "geyser", "giant", "giddy", "gift", "gigantic", "giggle",
  "ginger", "gingerbread", "giraffe", "girl", "give", "glacier", "glad", "glade", "gladly",
  "glamorous", "glance", "gland", "glare", "glass", "glaze", "gleam", "gleaming", "glen",
  "glide", "glider", "glimpse", "glisten", "glitter", "gloat", "globe", "gloomy", "glorious",
  "glory", "glossary", "glossy", "glove", "glow", "glowing", "glue", "gnaw", "go", "goalie",
  "goalpost", "goat", "gobble", "goes", "going", "gold", "golden", "goldfish", "gondola", "gone",
  "good", "goodness", "goose", "gopher", "gorge", "gorgeous", "gorilla", "gossip", "govern",
  "governor", "gown", "grab", "graceful", "gracious", "grade", "gradually", "grammar", "grand",
  "grandma", "grandpa", "granite", "granola", "grape", "grasp", "grass", "grasshopper",
  "grassland", "grateful", "gravel", "gravity", "gravy", "gray", "graze", "greasy", "great",
  "greatly", "greed", "greedy", "green", "greenhouse", "greet", "greyhound", "griddle", "grief",
  "grieve", "grill", "grim", "grimace", "grimy", "grin", "grind", "grip", "gritty", "grizzly",
  "groan", "grocer", "grocery", "groggy", "groom", "grope", "grouchy", "groundhog", "grove",
  "grow", "growl", "grubby", "gruff", "grumble", "grumpy", "grunt", "guard", "guess", "guest",
  "guide", "guilt", "gully", "gulp", "gum", "gumbo", "guppy", "gush", "gust", "gymnast",
  "gymnastics", "habit", "habitat", "had", "hail", "hair", "hairdresser", "hairy", "half",
  "halftime", "halibut", "hall", "hallway", "halt", "ham", "hamburger", "hammer", "hammock",
  "hamper", "hamster", "hand", "handball", "handkerchief", "handle", "handsome", "handwriting",
  "handy", "hang", "hangar", "hangnail", "happily", "happiness", "happy", "harbor", "hard",
  "hardly", "hardy", "hare", "harm", "harmless", "harmony", "harsh", "harvest", "has", "hash",
  "hasty", "hat", "hatch", "haul", "haunted", "have", "hawk", "hazard", "hazelnut", "hazy", "he",
  "head", "headlight", "heal", "health", "healthy", "heap", "heart", "heartbeat", "hearth",
  "hearty", "heat", "heave", "heavenly", "heavily", "heavy", "hedge", "hedgehog", "heel",
  "hefty", "helicopter", "helmet", "help", "helpful", "helpless", "hemisphere", "hen", "hence",
  "henceforth", "here", "hereby", "heritage", "hero", "heroic", "heroism", "heron", "hesitate",
  "hi", "hiccup", "hidden", "hide", "hideout", "high", "highlighter", "highly", "highway",
  "hike", "hiking", "hilarious", "hill", "hillside", "hinder", "hinge", "hint", "hip", "hippo",
  "hire", "hiss", "historian", "history", "hoard", "hobble", "hockey", "hoist", "holiday",
  "hollow", "home", "homely", "homestead", "homework", "honest", "honestly", "honesty", "honey",
  "honk", "honor", "hood", "hoodie", "hop", "hope", "hopeful", "hopefully", "hopscotch",
  "horizon", "hormone", "hornet", "horrible", "horse", "hospital", "hot", "hotdog", "hotel",
  "hound", "hour", "hover", "hovercraft", "however", "howl", "hubcap", "hug", "huge", "hum",
  "humble", "humid", "hummingbird", "hummus", "humor", "hunch", "hunger", "hungry", "hunt",
  "hunter", "hurdle", "hurl", "hurricane", "hurry", "hurt", "hush", "husky", "hut", "hutch",
  "hydrant", "hyena", "ice", "iceberg", "icicle", "icing", "icy", "idea", "identical", "idle",
  "if", "igloo", "ignorant", "ignore", "iguana", "illegal", "illustrate", "imaginary",
  "imagination", "imagine", "imitate", "immediately", "immense", "impala", "import", "important",
  "impossible", "impressive", "improve", "impulse", "in", "include", "increase", "incredible",
  "indeed", "independent", "index", "indoors", "inflate", "inform", "ingredient", "inhale",
  "initially", "injure", "ink", "inlet", "inn", "inning", "innocence", "innocent", "inquire",
  "inquisitive", "insect", "insert", "insist", "inspect", "inspire", "install", "instead",
  "instinct", "instruct", "instrument", "intelligent", "intend", "interesting", "interrupt",
  "intersection", "into", "introduce", "invent", "inventor", "invest", "investigate",
  "invisible", "invite", "iron", "is", "island", "it", "itch", "itchy", "ivy", "jab", "jackal",
  "jacket", "jag", "jagged", "jaguar", "jalapeno", "jalopy", "jam", "janitor", "jar", "jaw",
  "jawbone", "jealous", "jealousy", "jeans", "jeep", "jelly", "jellyfish", "jerk", "jersey",
  "jet", "jetpack", "jetway", "jewel", "jeweler", "jiggle", "jingle", "joey", "jog", "jogging",
  "join", "joke", "jolly", "jolt", "jostle", "journal", "journalist", "journey", "joy", "joyful",
  "judge", "judo", "juggle", "juggler", "juice", "juicy", "jumble", "jumbo", "jump", "jumper",
  "jumprope", "jumpy", "junction", "jungle", "just", "justice", "kangaroo", "karate", "kayak",
  "keen", "keep", "kennel", "ketchup", "kettle", "key", "kick", "kickball", "kid", "kidney",
  "kilt", "kind", "kindergarten", "kindle", "kindly", "kindness", "king", "kingdom", "kiosk",
  "kiss", "kitchen", "kitten", "kiwi", "knead", "knee", "kneel", "knew", "knife", "knight",
  "knit", "knobby", "knock", "knot", "know", "knowledge", "knuckle", "koala", "label",
  "laboratory", "lace", "lacrosse", "lad", "ladder", "ladle", "lady", "lag", "lagoon", "lake",
  "lamb", "lamp", "lampshade", "land", "landmark", "landslide", "lane", "language", "lanky",
  "lantern", "lap", "large", "lasagna", "laser", "lash", "lasso", "last", "lasting", "late",
  "lately", "laugh", "laughter", "launch", "laundry", "lava", "lavish", "lawful", "lawyer",
  "layer", "lazy", "leaf", "leafy", "leaky", "lean", "leap", "learn", "leathery", "lecture",
  "leg", "legal", "legend", "leggings", "leisure", "lemon", "lend", "lengthen", "lengthy",
  "lens", "leopard", "leotard", "lesson", "letter", "lettuce", "level", "lever", "liberty",
  "librarian", "library", "lick", "licorice", "lifeboat", "lifeguard", "lift", "ligament",
  "light", "lighthouse", "lightly", "lightning", "lightweight", "likable", "likewise", "lily",
  "limb", "limber", "lime", "limousine", "limp", "linger", "lion", "lip", "liquid", "listen",
  "liter", "litter", "little", "lively", "living", "lizard", "llama", "loaf", "loan", "lobby",
  "lobster", "locate", "lock", "locker", "locomotive", "locust", "lodge", "logic", "lollipop",
  "lonely", "lonesome", "long", "longing", "look", "lookout", "loose", "loosen", "lose", "loud",
  "loudly", "lounge", "lovable", "love", "lovely", "low", "lower", "loyal", "loyalty", "luck",
  "lucky", "lug", "luggage", "lukewarm", "lull", "lumberjack", "lumpy", "lunar", "lunch", "lung",
  "lunge", "lurch", "lurk", "luscious", "lush", "luxury", "lynx", "macaroni", "macaw", "machine",
  "mad", "madden", "made", "magic", "magical", "magician", "magnet", "magnificent", "magnifier",
  "magnify", "magpie", "mailbox", "maintain", "majestic", "make", "mall", "mammoth", "manage",
  "manatee", "mango", "mansion", "mantel", "mantis", "many", "map", "maple", "marathon",
  "marble", "marbles", "march", "mark", "marker", "market", "marmalade", "marrow", "marsh",
  "marshmallow", "marvel", "marvelous", "mash", "massive", "match", "math", "mathematics",
  "matter", "mattress", "mature", "mayonnaise", "mayor", "maze", "meadow", "meager", "mean",
  "meanwhile", "measly", "measure", "meat", "meatloaf", "meaty", "mechanic", "meddle",
  "medicine", "meek", "meerkat", "meet", "mellow", "melodic", "melon", "melt", "memorial",
  "memorize", "memory", "mend", "mention", "menu", "meow", "merchant", "mercury", "mercy",
  "merely", "merit", "merry", "mesa", "messy", "metal", "metallic", "meteor", "meteorite",
  "method", "microscope", "microwave", "mighty", "mild", "milk", "mill", "mimic", "mince",
  "mine", "miner", "mineral", "mingle", "minister", "minivan", "minnow", "minor", "mint",
  "minty", "minus", "minute", "miracle", "mirror", "mischief", "miserable", "misery", "mist",
  "mistake", "misty", "mitt", "mitten", "mix", "mixer", "mixture", "moan", "moccasin", "mock",
  "model", "modern", "modest", "moist", "moisten", "moisture", "molar", "mold", "moldy", "mole",
  "molecule", "mom", "moment", "mongoose", "monorail", "monsoon", "month", "monument", "mood",
  "moon", "moor", "moose", "mop", "mope", "moped", "mopey", "more", "morning", "mosaic",
  "mosquito", "moss", "most", "mostly", "motel", "moth", "mother", "motion", "motionless",
  "motivate", "motorbike", "motorboat", "motorcycle", "mound", "mount", "mountain",
  "mountainous", "mourn", "mouse", "mouth", "move", "mow", "mozzarella", "much", "mud", "muddle",
  "muddy", "mudroom", "mudslide", "muffin", "muffled", "muffler", "mug", "muggy", "mule",
  "multiply", "mumble", "munch", "mural", "murky", "murmur", "muscle", "museum", "mushroom",
  "mushy", "musical", "musician", "muskrat", "must", "mustache", "mustard", "musty", "mutter",
  "my", "mysterious", "mystery", "nab", "nag", "nail", "naive", "name", "nanny", "nap", "napkin",
  "narrow", "narwhal", "nasty", "natural", "nature", "naughty", "navigate", "nearby", "nearly",
  "neat", "neck", "necklace", "nectar", "need", "needle", "needy", "negative", "neglect",
  "neighbor", "neighborhood", "neither", "nerve", "nervous", "nestle", "netball", "nevertheless",
  "new", "newt", "next", "nibble", "nice", "nickel", "nifty", "night", "nightgown",
  "nightingale", "nightstand", "nimble", "nine", "no", "noble", "nobody", "nod", "noisy",
  "nominate", "nonetheless", "nonstop", "noodle", "nook", "noon", "normal", "nose", "nostril",
  "nosy", "note", "notebook", "nothing", "notice", "notify", "notion", "nourish", "novelist",
  "nowadays", "nowhere", "nudge", "nugget", "number", "numeral", "numerous", "nurse", "nut",
  "nutmeg", "nutritious", "nutty", "oasis", "oat", "oatmeal", "obey", "object", "oblong",
  "observatory", "observe", "obtain", "obvious", "obviously", "occasionally", "occupy", "occur",
  "ocean", "ocelot", "octopus", "odd", "odometer", "of", "offend", "offense", "offer", "often",
  "oily", "old", "olive", "omelet", "omit", "on", "once", "one", "onion", "only", "onward",
  "opaque", "open", "openly", "operate", "opinion", "opossum", "oppose", "or", "orange",
  "orangutan", "orbit", "orchard", "order", "orderly", "ordinary", "oregano", "organ",
  "organize", "original", "ostrich", "other", "otherwise", "otter", "ourselves", "outdoor",
  "outdoors", "outfield", "outline", "outpost", "outrageous", "outside", "outward", "oval",
  "oven", "over", "overall", "overalls", "overcast", "overcoat", "overcome", "overflow",
  "overhead", "overhear", "overjoyed", "overpass", "owe", "owl", "own", "ox", "oxygen", "oyster",
  "ozone", "pace", "pack", "package", "padded", "paddle", "painful", "paint", "painter", "pair",
  "pajama", "pajamas", "pal", "palace", "pale", "palm", "pamper", "pan", "pancake", "panda",
  "pant", "panther", "pantry", "pants", "paper", "parachute", "parade", "paragraph", "parakeet",
  "paramedic", "pardon", "parent", "park", "parka", "parlor", "parrot", "parsley", "parsnip",
  "part", "particle", "partly", "passenger", "pasta", "paste", "pastel", "pastry", "pasture",
  "pat", "patch", "patchy", "path", "patient", "patio", "pattern", "pause", "pave", "pavement",
  "pavilion", "pea", "peaceful", "peach", "peacock", "peanut", "pear", "peas", "pebble", "peck",
  "peculiar", "pedal", "peek", "peel", "peep", "pelican", "pencil", "pendulum", "penguin",
  "people", "pepper", "perch", "perfect", "perfectly", "perform", "perhaps", "periscope",
  "perish", "perky", "permit", "person", "personally", "persuade", "pesky", "pester", "petal",
  "petite", "pharmacist", "pheasant", "phone", "phony", "photo", "photograph", "photographer",
  "pianist", "piano", "pick", "pickle", "picky", "pier", "pierce", "pig", "pigeon", "piglet",
  "pillar", "pillow", "pillowcase", "pilot", "pimple", "pinch", "pineapple", "pinecone", "pink",
  "piranha", "pirate", "pitch", "pitcher", "pizza", "place", "plain", "plan", "plane", "planet",
  "plank", "plant", "plaster", "plate", "plateau", "platform", "platypus", "play", "playful",
  "playground", "plaza", "plead", "pleasant", "please", "pledge", "plentiful", "plod", "plot",
  "plow", "pluck", "plug", "plum", "plumber", "plump", "plunge", "plunger", "plus", "plush",
  "pocket", "poem", "poet", "point", "pointy", "poke", "pole", "policeman", "polish", "polished",
  "polite", "politely", "politician", "pollen", "poncho", "pond", "ponder", "pontoon", "pony",
  "poodle", "poor", "poorly", "pop", "popcorn", "popsicle", "popular", "porch", "porcupine",
  "pore", "pork", "porpoise", "porridge", "port", "portal", "positive", "possible", "possibly",
  "possum", "postbox", "poster", "postman", "posture", "pot", "potato", "potter", "pounce",
  "pour", "pout", "powder", "powerful", "practice", "prairie", "praise", "prance", "prattle",
  "prawn", "pray", "preach", "precious", "precise", "precisely", "predict", "prefer", "prepare",
  "preschool", "present", "presently", "preserve", "president", "press", "pressure", "pretend",
  "pretty", "pretzel", "prevent", "previously", "prick", "prickly", "principal", "print",
  "prism", "private", "prize", "prized", "problem", "produce", "professor", "project", "promise",
  "promote", "prompt", "promptly", "pronoun", "propeller", "proper", "properly", "propose",
  "protect", "protective", "protest", "protractor", "proud", "proudly", "prove", "provide",
  "prowl", "prudent", "prune", "pry", "publish", "pudding", "puddle", "puffin", "puffy", "pull",
  "pulley", "pullover", "pulse", "puma", "pump", "pumpkin", "punch", "punctual", "punctually",
  "punctuation", "puncture", "punish", "puny", "pupil", "puppy", "purchase", "purple",
  "purposely", "purr", "push", "puzzle", "pyramid", "python", "quack", "quail", "quaint",
  "quake", "quarry", "quarterback", "quartz", "queen", "quench", "quest", "question", "quick",
  "quickly", "quiet", "quietly", "quill", "quilt", "quip", "quirky", "quit", "quite", "quiver",
  "quiz", "quote", "rabbit", "raccoon", "race", "racket", "radar", "radiator", "radio", "radish",
  "radius", "raft", "rafting", "raid", "rail", "railing", "railroad", "railway", "rain",
  "rainbow", "raincoat", "rainfall", "rainy", "raise", "raisin", "rake", "ram", "ramble", "ramp",
  "rampart", "ranch", "ranger", "rap", "rapid", "rapidly", "rare", "rarely", "rash", "raspberry",
  "rasping", "raspy", "rat", "rate", "rather", "rattle", "rattling", "ravine", "reach", "react",
  "reactor", "read", "readily", "reading", "ready", "real", "realize", "really", "reap", "rear",
  "reason", "reasonable", "rebel", "rebellious", "receive", "recent", "recently", "recess",
  "recipe", "recite", "reckless", "recline", "recognize", "recommend", "record", "recover",
  "rectangular", "recycle", "red", "reduce", "reef", "referee", "reflect", "reflection",
  "refreshing", "refrigerator", "refuse", "region", "regret", "regular", "regularly", "rehearse",
  "reindeer", "reject", "rejoice", "relax", "relaxed", "relay", "release", "reliable", "relieve",
  "rely", "remain", "remarkable", "remember", "remind", "remote", "remove", "render", "repair",
  "repeat", "repeatedly", "replace", "reply", "report", "reporter", "represent", "request",
  "require", "rescue", "resemble", "reserve", "reservoir", "resist", "responsible", "rest",
  "restless", "restore", "retreat", "return", "reveal", "reverse", "review", "reward", "rhino",
  "rhubarb", "rhyme", "rib", "ribcage", "rice", "rich", "rickshaw", "riddle", "ride", "ridge",
  "righteous", "ring", "rink", "rinse", "rip", "ripe", "ripen", "ripple", "rise", "risk",
  "risky", "river", "riverbank", "riverbed", "road", "roam", "roar", "roaring", "roast", "rob",
  "robe", "robin", "robust", "rock", "rocket", "rockslide", "rocky", "roll", "romp", "roof",
  "rooftop", "rooster", "root", "rosy", "rot", "rotten", "rough", "roughly", "round", "rowboat",
  "rowdy", "rowing", "royal", "rub", "rubber", "rudder", "ruddy", "rudely", "rug", "rugged",
  "ruin", "rule", "ruler", "rumble", "rummage", "run", "runway", "rush", "rust", "rustle",
  "rusty", "sacred", "sad", "sadly", "safe", "safely", "sag", "sagebrush", "sail", "sailboat",
  "sailing", "sailor", "salad", "salamander", "salami", "saliva", "salmon", "salt", "salty",
  "salute", "sanctuary", "sand", "sandal", "sandstorm", "sandwich", "sandy", "sapling",
  "sardine", "sash", "satellite", "satisfied", "satisfy", "sauce", "saucepan", "sausage",
  "savage", "savanna", "save", "savor", "saw", "sawdust", "say", "scab", "scald", "scale",
  "scalp", "scaly", "scamper", "scan", "scanty", "scarce", "scarcely", "scare", "scared",
  "scarf", "scary", "scatter", "scenic", "scented", "scholar", "school", "science", "scientist",
  "scissors", "scoff", "scold", "scone", "scoop", "scooter", "scorch", "score", "scoreboard",
  "scornful", "scorpion", "scout", "scowl", "scraggly", "scramble", "scrape", "scratch",
  "scrawl", "scrawny", "scream", "screech", "scribble", "scrub", "scruffy", "scuba", "scuff",
  "sculptor", "seafood", "seahorse", "seal", "seaport", "search", "seashell", "seashore",
  "season", "seasoning", "seat", "seaweed", "seclude", "second", "secret", "secretary", "secure",
  "sediment", "seed", "seedling", "seek", "seesaw", "seize", "seldom", "select", "selfish",
  "sell", "semester", "senator", "send", "sense", "sensible", "sensitive", "sensor", "sentence",
  "separate", "serious", "seriously", "serve", "settee", "settle", "seven", "severe", "sew",
  "shabby", "shack", "shade", "shadow", "shadowy", "shady", "shaggy", "shake", "shaky",
  "shallow", "shameful", "shanty", "shape", "share", "shark", "sharp", "sharpen", "sharply",
  "shatter", "shave", "shawl", "shed", "sheep", "sheer", "sheet", "shelf", "shell", "shelter",
  "sherbet", "sheriff", "shield", "shift", "shifty", "shimmer", "shin", "shine", "shingle",
  "shiny", "ship", "shipyard", "shirt", "shiver", "shivery", "shock", "shocking", "shoe", "shoo",
  "shoot", "shop", "shore", "shoreline", "short", "shorten", "shortly", "shorts", "shoulder",
  "shout", "shove", "shovel", "show", "shower", "shred", "shrew", "shriek", "shrimp", "shrine",
  "shrink", "shrub", "shrug", "shudder", "shuffle", "shun", "shush", "shut", "shutter", "shy",
  "shyly", "sick", "sickly", "sidecar", "sidewalk", "sift", "sigh", "sign", "signal", "signpost",
  "silent", "silently", "silky", "silly", "silo", "silver", "simmer", "simple", "simply",
  "sincere", "sincerely", "sinew", "sing", "singer", "sink", "sip", "sister", "sit", "six",
  "sixth", "sizzle", "sizzling", "skate", "skateboard", "skating", "skeleton", "sketch", "ski",
  "skid", "skiing", "skillet", "skim", "skin", "skinny", "skip", "skirt", "skitter", "skittish",
  "skull", "skunk", "sky", "skyline", "skyscraper", "slacks", "slam", "slap", "slash", "sled",
  "sledding", "sledge", "sleek", "sleep", "sleepy", "sleet", "sleigh", "slender", "slice",
  "slide", "slightly", "slim", "slimy", "slingshot", "slink", "slip", "slipper", "slippery",
  "slither", "slobber", "slope", "sloppy", "sloth", "slouch", "slow", "slowly", "sludgy", "slug",
  "slump", "slurp", "slush", "smack", "small", "smart", "smash", "smear", "smell", "smelly",
  "smile", "smoggy", "smoke", "smoky", "smooth", "smoothie", "smoothly", "smother", "smudge",
  "smug", "snack", "snail", "snake", "snap", "snappy", "snarl", "snatch", "sneak", "sneaker",
  "sneaky", "sneer", "sneeze", "sniff", "sniffle", "snip", "snobby", "snoop", "snooze", "snore",
  "snorkel", "snort", "snow", "snowball", "snowboard", "snowdrift", "snowfall", "snowflake",
  "snowman", "snowmobile", "snowy", "snug", "snuggle", "so", "soak", "soaked", "soap", "soar",
  "soaring", "sob", "soccer", "sociable", "sock", "sofa", "soft", "softball", "soften", "softly",
  "soggy", "soil", "solar", "soldier", "sole", "solemn", "solid", "solve", "somber", "some",
  "somebody", "somehow", "someone", "somersault", "something", "sometime", "sometimes",
  "somewhat", "somewhere", "soon", "soothe", "soothing", "sopping", "sore", "sorrowful", "sort",
  "soulful", "sound", "soundly", "soup", "sour", "sourdough", "space", "spaceship", "spacious",
  "spaghetti", "spank", "spare", "spark", "sparkle", "sparkling", "sparrow", "spatter",
  "spatula", "speak", "spear", "special", "specify", "specimen", "speckle", "speckled",
  "spectrum", "speedboat", "speedy", "spell", "spelling", "spend", "sphere", "spice", "spicy",
  "spider", "spiky", "spill", "spin", "spinach", "spine", "spineless", "spiral", "spire", "spit",
  "splash", "splashdown", "splatter", "splendid", "splinter", "split", "splutter", "spoil",
  "sponge", "spongy", "sponsor", "spook", "spooky", "spoon", "spot", "spotless", "spotted",
  "spout", "sprain", "sprawl", "spray", "spread", "sprightly", "spring", "springy", "sprinkle",
  "sprint", "sprout", "spurt", "sputter", "spy", "squabble", "square", "squash", "squawk",
  "squeak", "squeaky", "squeal", "squeeze", "squid", "squint", "squirm", "squirrel", "squirt",
  "squishy", "stable", "stack", "stadium", "stagecoach", "stagger", "stain", "staircase",
  "stairway", "stairwell", "stalactite", "stalagmite", "stale", "stalk", "stall", "stallion",
  "stammer", "stamp", "stand", "standard", "stapler", "star", "stare", "starfish", "start",
  "startle", "startled", "starve", "stash", "station", "statue", "stay", "steadily", "steady",
  "steak", "steal", "stealthy", "steam", "steamboat", "steamship", "steamy", "steel", "steep",
  "steeple", "steer", "steering", "stem", "step", "stern", "sternly", "stew", "stick", "sticky",
  "stiff", "stiffen", "still", "sting", "stingray", "stingy", "stink", "stinky", "stir",
  "stitch", "stockade", "stocking", "stomach", "stomp", "stone", "stool", "stoop", "stop",
  "stopwatch", "store", "stork", "storm", "stormy", "story", "stout", "stove", "stow",
  "straddle", "straight", "straighten", "strain", "strange", "strap", "strawberry", "stray",
  "streak", "stream", "street", "stretch", "strict", "strictly", "stride", "strike", "striking",
  "string", "strip", "striped", "strive", "stroke", "stroll", "strong", "strongly", "struggle",
  "strum", "strut", "stubborn", "student", "studio", "study", "stuff", "stuffing", "stuffy",
  "stumble", "stun", "stunning", "stupendous", "sturdy", "stutter", "stylish", "subject",
  "submarine", "substance", "subtract", "suburb", "subway", "succeed", "such", "suck", "sudden",
  "suddenly", "suede", "suffer", "sugar", "sugary", "suggest", "sulfur", "sum", "summer",
  "summit", "summon", "sun", "sunbeam", "sundae", "sundial", "sundown", "sunflower", "sunhat",
  "sunlight", "sunny", "sunrise", "sunroom", "sunset", "sunshine", "sunspot", "super", "superb",
  "supper", "supply", "support", "suppose", "supreme", "sure", "surely", "surf", "surface",
  "surfboard", "surfing", "surgeon", "surprise", "surprised", "surrender", "surround", "survive",
  "sushi", "suspect", "suspend", "suspenders", "swallow", "swamp", "swampy", "swan", "swap",
  "swarm", "sway", "swear", "sweat", "sweatband", "sweater", "sweatpants", "sweatshirt",
  "sweaty", "sweep", "sweet", "swell", "swerve", "swift", "swiftly", "swim", "swimming", "swing",
  "swipe", "swirl", "switch", "swoop", "syllable", "symbol", "syrup", "system", "table",
  "tablet", "tackle", "taco", "tadpole", "tag", "tailor", "talented", "talk", "tall", "tally",
  "tame", "tan", "tangerine", "tangle", "tangled", "tangy", "tanker", "tap", "tape", "tarantula",
  "tart", "taste", "tasty", "tattered", "tavern", "taxi", "taxicab", "teach", "teacher",
  "teammate", "teapot", "tear", "tease", "teaspoon", "teeny", "telescope", "tell", "teller",
  "temperature", "temple", "tempt", "ten", "tend", "tender", "tenderly", "tendon", "tenement",
  "tennis", "tense", "tent", "terminal", "termite", "terrible", "terrier", "terrific", "terrify",
  "test", "tetherball", "textbook", "texture", "than", "thank", "thankful", "thankfully", "that",
  "thaw", "theater", "them", "then", "there", "thereby", "therefore", "thermometer",
  "thermostat", "thesaurus", "these", "they", "thick", "thicket", "thigh", "thin", "thing",
  "think", "thirsty", "this", "thistle", "thorn", "thorny", "thoroughly", "those", "thoughtful",
  "thrash", "thread", "threaten", "three", "threshold", "thrilling", "thrive", "throat", "throb",
  "throttle", "throughout", "throw", "thrust", "thumb", "thump", "thunder", "thunderous",
  "thunderstorm", "thus", "tiara", "tickle", "tide", "tidy", "tie", "tiger", "tight", "tighten",
  "tightly", "tilt", "timber", "time", "timeline", "timid", "tingle", "tinker", "tiny", "tip",
  "tiptoe", "tire", "tired", "tireless", "tissue", "toad", "toadstool", "toast", "toaster",
  "toasty", "today", "toddle", "toe", "toenail", "together", "toil", "toilet", "told", "toll",
  "tollbooth", "tomato", "tomorrow", "tongue", "tonight", "tonsil", "took", "toolbox", "toot",
  "tooth", "topple", "topsoil", "torch", "tornado", "tortilla", "tortoise", "toss", "total",
  "toucan", "touch", "touchdown", "tough", "tour", "tournament", "tow", "towel", "tower",
  "towering", "town", "township", "toy", "trace", "tractor", "trade", "traffic", "tragic",
  "trail", "trailer", "train", "trainer", "trample", "trampoline", "tranquil", "transform",
  "transit", "translate", "transparent", "transport", "trap", "trapper", "travel", "tread",
  "treadmill", "treasure", "treat", "tree", "treehouse", "treetop", "trek", "tremble", "tremor",
  "trench", "trendy", "trick", "trickle", "tricky", "trim", "trip", "triumph", "triumphant",
  "trolley", "trophy", "tropic", "tropical", "trot", "trouble", "trousers", "trout", "truck",
  "trudge", "truly", "trust", "trusty", "truthful", "tub", "tubby", "tuck", "tug", "tugboat",
  "tumble", "tumbleweed", "tuna", "tundra", "tune", "tunic", "tunnel", "turkey", "turn",
  "turnip", "turnpike", "turret", "turtle", "turtleneck", "tutor", "tuxedo", "twig", "twin",
  "twinkle", "twinkling", "twirl", "twist", "twisty", "twitch", "two", "type", "typically",
  "ugly", "ultimate", "ultimately", "umbrella", "umpire", "unavailable", "unbeaten", "uncertain",
  "uncle", "uncommon", "under", "underbrush", "underground", "underline", "underneath",
  "undershirt", "understand", "undo", "undress", "uneven", "unfair", "unfold", "unfortunately",
  "unhappy", "unicycle", "uniform", "unique", "unite", "universe", "unkind", "unless", "unlock",
  "unlucky", "unpack", "unpleasant", "unruly", "untie", "until", "unusual", "unwrap", "up",
  "upbeat", "uphold", "upon", "upright", "upset", "upstairs", "upward", "upwards", "urge",
  "urgent", "us", "use", "used", "useful", "useless", "usher", "usual", "usually", "utterly",
  "vacant", "vacuum", "vague", "vaguely", "valiant", "valley", "valuable", "van", "vanilla",
  "vanish", "vapor", "vary", "vase", "vast", "vastly", "vault", "vegetable", "vehicle", "vein",
  "velvet", "velvety", "vent", "venture", "verify", "very", "vessel", "vest", "vet",
  "veterinarian", "vex", "vibrant", "vibrate", "vicious", "victorious", "vigilant", "villa",
  "village", "vine", "vinegar", "vineyard", "violent", "violinist", "visit", "vivid",
  "vocabulary", "vocal", "voiceless", "volcano", "volleyball", "voltage", "volume", "volunteer",
  "vote", "vow", "voyage", "vulture", "wacky", "wade", "waffle", "wag", "wager", "wagon", "wail",
  "waist", "wait", "waiter", "waitress", "wake", "waken", "walk", "walkway", "wall", "wallaby",
  "wallow", "wallpaper", "walnut", "walrus", "wander", "wandering", "want", "warble", "wardrobe",
  "warm", "warn", "warp", "warthog", "wary", "wash", "washer", "wasp", "waste", "wastebasket",
  "wasteful", "watch", "watchful", "water", "waterfall", "watermelon", "watershed", "watery",
  "wave", "waver", "wax", "we", "weak", "weaken", "wealthy", "wear", "wearily", "weary",
  "weasel", "weather", "weave", "webbed", "wed", "weed", "week", "weekly", "weep", "weepy",
  "weigh", "weight", "weird", "welcome", "weld", "welder", "well", "went", "were", "wet",
  "whack", "whale", "wharf", "what", "wheat", "wheelbarrow", "wheeze", "when", "where",
  "wherever", "which", "while", "whimper", "whimsical", "whine", "whip", "whir", "whirl",
  "whirlpool", "whirlwind", "whisk", "whisper", "whistle", "white", "whittle", "whiz", "wholly",
  "whopping", "wicked", "wide", "widely", "widen", "wield", "wiggle", "wiggly", "wild",
  "wilderness", "wildfire", "wildflower", "wildly", "will", "willing", "willingly", "willow",
  "wilt", "wilted", "win", "wince", "wind", "windbreaker", "windmill", "window", "windowsill",
  "windpipe", "windshield", "windstorm", "windy", "wink", "winning", "winter", "wintry", "wipe",
  "wire", "wiry", "wise", "wisely", "wish", "with", "withdraw", "wither", "witty", "wobble",
  "wobbly", "wolf", "woman", "wonder", "wonderful", "wood", "wooden", "woodland", "woodpecker",
  "woolly", "woozy", "word", "wordy", "work", "workbook", "worksheet", "workshop", "worldly",
  "worm", "worried", "worry", "worship", "worthless", "worthy", "would", "wound", "wounded",
  "wrap", "wreck", "wren", "wrench", "wrestle", "wrestling", "wriggle", "wring", "wrinkle",
  "wrinkled", "wrist", "write", "writer", "wrong", "yacht", "yam", "yank", "yard", "yardstick",
  "yawn", "year", "yearly", "yearn", "yeast", "yell", "yellow", "yellowish", "yelp", "yesterday",
  "yield", "yodel", "yoga", "yogurt", "young", "your", "youthful", "yummy", "zany", "zap",
  "zealous", "zebra", "zero", "zesty", "zigzag", "zip", "zipper", "zippy", "zone", "zoo", "zoom",
  "zucchini",
];

export const WORDS_PER_LINE = 6;
export const LINES_PER_ROUND = 3;
export const WORDS_PER_ROUND = WORDS_PER_LINE * LINES_PER_ROUND;

// Splits a flat list of words into { start, end } character offsets into
// `words.join(" ")`, grouping wordsPerLine words per row for display. Each
// row's end absorbs the separator space before the next row, so every
// character of the joined string belongs to exactly one row.
export function splitIntoLines(words, wordsPerLine) {
  let offset = 0;
  const rows = [];
  for (let i = 0; i < words.length; i += wordsPerLine) {
    const group = words.slice(i, i + wordsPerLine);
    const isLastGroup = i + wordsPerLine >= words.length;
    const start = offset;
    let end = start + group.join(" ").length;
    if (!isLastGroup) end += 1;
    rows.push({ start, end });
    offset = end;
  }
  return rows;
}

export function randomWords(words, count) {
  const shuffled = [...words].sort(() => Math.random() - 0.5);
  if (shuffled.length >= count) return shuffled.slice(0, count);
  const result = [...shuffled];
  while (result.length < count) {
    result.push(words[Math.floor(Math.random() * words.length)]);
  }
  return result;
}
